### PR TITLE
Do minor improvements to fixup processing and creation of routing schema

### PR DESCRIPTION
**Pull request by jarkkoka**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34)

### CODE REVIEW

**Review by culka — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`sql/routing/create_routing_schema.sql` line 226 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34#-N4gOhYBDZLZxeezgllQ:-N4gOhYBDZLZxeezgllR:b-l0ulce) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/d5705a7619651046b8bd2108479c18d422ef55bb/sql/routing/create_routing_schema.sql#L226)):*
> ```TSQL
>     'Topology nodes created for infrastructure links by pgRougting';
> 
> SELECT pgr_analyzeGraph(:'schema' || '.infrastructure_link', 0.001, 'geom', 'infrastructure_link_id', 'start_node_id', 'end_node_id');
> ```

This prints out some information when the script runs, but should the output be saved somewhere? Or raise an error if the analysis fails.
___
*[`sql/routing/create_routing_schema.sql` line 259 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34#-N4gRuQl2udp1SDDO8ak:-N4gRuQl2udp1SDDO8al:b5i50yt) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/d5705a7619651046b8bd2108479c18d422ef55bb/sql/routing/create_routing_schema.sql#L259)):*
> ```TSQL
> -- Analyse one-way streets. A couple of columns in `infrastructure_link_vertices_pgr` table are
> -- populated as side effect.
> SELECT pgr_analyzeOneWay(:'schema' || '.infrastructure_link', ARRAY['', 'B', 'TF'], ARRAY['', 'B', 'FT'], ARRAY['', 'B', 'FT'], ARRAY['', 'B', 'TF'], oneway:='pgr_dir', source:='start_node_id', target:='end_node_id');
> ```

Same comment here, this could be useful information that could be saved?

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`sql/routing/create_routing_schema.sql` line 226 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34#-N4gOhYBDZLZxeezgllQ:-N4gmi_u4KAal5X6DyIo:b-77e0cq) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/d5705a7619651046b8bd2108479c18d422ef55bb/sql/routing/create_routing_schema.sql#L226)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

This prints out some information when the script runs, but should the output be saved somewhere? Or raise an error if the analysis fails.
</blockquote></details>

What do you think would be a reason to save the output? IMO one could go to check github workflow logs to see what the last output was or execute the script locally to check topology analysis. Until we see actual errors in Digiroad topology I would not put effort into error handling.

The point of this PR was just perform the analysis. Anything beyond that is a topic of its own PR.
___
*[`sql/routing/create_routing_schema.sql` line 259 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34#-N4gRuQl2udp1SDDO8ak:-N4gmVPN1v4XKBm5KHjc:b-lkcex) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/d5705a7619651046b8bd2108479c18d422ef55bb/sql/routing/create_routing_schema.sql#L259)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Same comment here, this could be useful information that could be saved?
</blockquote></details>

There is actually data saved into columns of table `infrastructure_link_vertices_pgr`.

Of course, one could go to check github workflow logs to see what the output was. But besides that I do not currently see a reason to store the debug data into any specific place since the output is repeatable.

**Review by culka — APPROVED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`sql/routing/create_routing_schema.sql` line 259 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34#-N4gRuQl2udp1SDDO8ak:-N4gqmjrD3WAEtKKPm-x:bfge3bg) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/d5705a7619651046b8bd2108479c18d422ef55bb/sql/routing/create_routing_schema.sql#L259)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

There is actually data saved into columns of table `infrastructure_link_vertices_pgr`.

Of course, one could go to check github workflow logs to see what the output was. But besides that I do not currently see a reason to store the debug data into any specific place since the output is repeatable.
</blockquote></details>

Previously, the columns affected were left NULL values. After this PR, the columns are populated with data.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`sql/routing/create_routing_schema.sql` line 226 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/34#-N4gOhYBDZLZxeezgllQ:-N4hDnYP5Cn-BBYOTQtH:b-jbtgw9) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/d5705a7619651046b8bd2108479c18d422ef55bb/sql/routing/create_routing_schema.sql#L226)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

What do you think would be a reason to save the output? IMO one could go to check github workflow logs to see what the last output was or execute the script locally to check topology analysis. Until we see actual errors in Digiroad topology I would not put effort into error handling.

The point of this PR was just perform the analysis. Anything beyond that is a topic of its own PR.
</blockquote></details>

To be more precise, the analysis itself does not fail. It just reports issues related to the topology.

**Pull request merged**
