### PR TITLE
Add proper support for QGIS fixup layer in GeoPackage format.

### PR DESCRIPTION
**Pull request by jarkkoka**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33)

### CODE REVIEW

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @jschummer and @pallost)

___
*[`sql/apply_fixup_layer.sql` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33#-N33gPbZ7UhCrcbTRsW3:-N33gPbZ7UhCrcbTRsW4:bcab3fm) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/e5108e108d5b86455f90d35edfa6a0eeb2dada55/sql/apply_fixup_layer.sql#L10)):*
> ```TSQL
> -- Force separate ID value spaces for fixup data.
> UPDATE :schema.fix_layer_link
> SET link_id     = 'hsl_' || fid,
> ```

In the last commit of PR, I changed `link_id` attribute to be derived from the `fid` column of GeoPackage because it is unique. Hence, no need to verify uniqueness separately.

However, this might introduce an issue where removing a link (perhaps accidentally) in QGIS and recreating it will assign a different `fid` to the original link. This may or may not be a problem later when updating more recent revisions Digiroad infrastructure links to JORE4.



_Code quote:_
```TSQL
link_id     = 'hsl_' || fid
```
___
*[`sql/apply_fixup_layer.sql` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33#-N33hha16diHKJwtXeUQ:-N33hha16diHKJwtXeUR:b4t02nr) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/e5108e108d5b86455f90d35edfa6a0eeb2dada55/sql/apply_fixup_layer.sql#L11)):*
> ```TSQL
> UPDATE :schema.fix_layer_link
> SET link_id     = 'hsl_' || fid,
>     internal_id =  1000000000 + fid;  -- add one billion (US)
> ```

By adding `1_000_000_000` it is tried to keep ID spaces for (1) Digiroad-originated and (2) HSL-custom links apart from each other.

`internal_id` is used e.g. as the internal primary key in JORE4 map-matching service.



_Code quote:_
```TSQL
internal_id =  1000000000 + fid;  -- add one billion (US)
```

**Review by jschummer — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`sql/apply_fixup_layer.sql` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33#-N33gPbZ7UhCrcbTRsW3:-N41EysdD_LuqJpxSnXa:b-p02skx) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/e5108e108d5b86455f90d35edfa6a0eeb2dada55/sql/apply_fixup_layer.sql#L10)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

In the last commit of PR, I changed `link_id` attribute to be derived from the `fid` column of GeoPackage because it is unique. Hence, no need to verify uniqueness separately.

However, this might introduce an issue where removing a link (perhaps accidentally) in QGIS and recreating it will assign a different `fid` to the original link. This may or may not be a problem later when updating more recent revisions Digiroad infrastructure links to JORE4.
</blockquote></details>

Maybe you could add a few words about this as a comment? (Not about what was present in the last commit, but about the general problem that an id may be reused under that circumstance.)
___
*[`sql/apply_fixup_layer.sql` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33#-N33hha16diHKJwtXeUQ:-N41FIe4BWPqKFc6wIsJ:b-cng0bj) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/e5108e108d5b86455f90d35edfa6a0eeb2dada55/sql/apply_fixup_layer.sql#L11)):*
> internal_id is used e.g. as the internal primary key in JORE4 map-matching service.

Maybe also this could be added to the comment?

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @pallost)

___
*[`sql/apply_fixup_layer.sql` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33#-N33gPbZ7UhCrcbTRsW3:-N41bC6v0lgrvKfioHX_:b-2t43mr) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/e5108e108d5b86455f90d35edfa6a0eeb2dada55/sql/apply_fixup_layer.sql#L10)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Maybe you could add a few words about this as a comment? (Not about what was present in the last commit, but about the general problem that an id may be reused under that circumstance.)
</blockquote></details>

Ok. Thanks for comment. Will add a comment about that.
___
*[`sql/apply_fixup_layer.sql` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33#-N33hha16diHKJwtXeUQ:-N41bJPv5NYQ6rTYYwdo:bu7ccg8) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import/blob/e5108e108d5b86455f90d35edfa6a0eeb2dada55/sql/apply_fixup_layer.sql#L11)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> internal_id is used e.g. as the internal primary key in JORE4 map-matching service.

Maybe also this could be added to the comment?
</blockquote></details>

Ok. Will do that also.

**Review by culka — APPROVED** [review]
> Reviewed 6 of 13 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import/33)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pallost)

**Pull request merged**
